### ISSUE TITLE
System.UriFormatException on MessageConfig.FileBaseDirectory with relative path.

### ISSUE THREAD

**Issue by rtieland** [axuno/MailMergeLib#18] opened 2018-08-22 08:23 UTC
When a relative path is used for the property FileBaseDirectory an exception System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.' is thrown.

For example:

FileBaseDirectory = ".\\Templates\\Attachments"; //Throws exception
FileBaseDirectory =  Path.Combine(Directory.GetCurrentDirectory(), "Templates\\Attachments"); //Doesn't thow exception.

**Comment by axunonb** [comment] 2018-08-31 07:33
This is by design:
1. The ```FileBaseDirectory``` must be an absolute path. The default currently is ```Path.GetTempPath()```.
2. The **file paths** (e.g. attachments) **are relative** to the ```FileBaseDirectory```.

I updated the xmldoc of the property accordingly.
Does this make sense to you?

**Comment by axunonb** [comment] 2018-09-05 21:58
Do you have a proposal to improve or should we close the issue?

**Comment by rtieland** [comment] 2018-09-06 05:03
The only improvement I can think of is check the path when it is set. Now there is only an exception when htmlbody is set and processed.
________________________________
Van: Norbert Bietsch <notifications@github.com>
verzonden: woensdag 5 september 2018 23:58
Aan: axuno/MailMergeLib
Cc: rtieland; Author
Onderwerp: Re: [axuno/MailMergeLib] System.UriFormatException on MessageConfig.FileBaseDirectory with relative path. (#18)


Do you have a proposal to improve or should we close the issue?

**Comment by axunonb** [comment] 2018-09-06 19:10
Commit https://github.com/axuno/MailMergeLib/commit/88ea35507b0a78d69c3aa1e3626e4cc7f581054f addresses your proposal: ```MessageConfig.FileBaseDir``` will now be checked for an absolute path. This is the earliest checkpoint. Issue resolved?

**Comment by rtieland** [comment] 2018-09-06 19:44
Yes that's perfect.
________________________________
Van: Norbert Bietsch <notifications@github.com>
verzonden: donderdag 6 september 2018 21:12
Aan: axuno/MailMergeLib
Cc: rtieland; Author
Onderwerp: Re: [axuno/MailMergeLib] System.UriFormatException on MessageConfig.FileBaseDirectory with relative path. (#18)


Commit 88ea355<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faxuno%2FMailMergeLib%2Fcommit%2F88ea35507b0a78d69c3aa1e3626e4cc7f581054f&data=02%7C01%7C%7C2faa451fe55a403493f508d6142cacb6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636718579433184922&sdata=JRRINtnFQQN4eVXIGy%2FJwy73JlWFU0Lg9Mgb17QeLNU%3D&reserved=0> addresses your proposal: MessageConfig.FileBaseDir will now be checked for an absolute path. This is the earliest checkpoint. Issue resolved?

**Comment by axunonb** [comment] 2018-12-29 21:57
It turned out in v5.6.0, that checking ```MessageConfig.FileBaseDir``` for a full path already when setting the property causes problems in a web environment, where the final full path is set after the ```MessageConfig``` is read from a configuration file.
In v5.6.1 the full path for ```MessageConfig.FileBaseDir``` will be checked while the ```MailMergeMessage```'s ```Send...``` or ```GetMimeMessage()``` methods are called.

**Comment by axunonb** [comment] 2018-12-29 22:08
Closed with release [v5.6.1.0](https://github.com/axuno/MailMergeLib/releases/tag/v5.6.1.0)

**Closed as completed** 2018-12-29 22:08 UTC
