### ISSUE TITLE
Don't enforce ContentEncoding.SevenBit wtih pure 7bit content

### ISSUE THREAD

**Issue by hades200082** [axuno/MailMergeLib#16] opened 2018-02-26 16:35 UTC
When using MailMergeLib I'm seeing some odd issues where occasionally a dot will go missing from the email content once it's received by the recipients.

This often manifests as broken links or images due to a dot in the URL is missing.

With some research it appears that the issue is to do with something called "dot stuffing".

> To allow all user composed text to be transmitted transparently, the following procedures are used:
> 
> 1. Before sending a line of mail text, the SMTP client checks the first character of the line. If it is a period, one additional period is inserted at the beginning of the line.
> 2. When a line of mail text is received by the SMTP server, it checks the line. If the line is composed of a single period, it is treated as the end of mail indicator. If the first character is a period and there are other characters on the line, the first character is deleted.

See http://tools.ietf.org/html/rfc5321#section-4.5.2

All I can find on Google is people suggesting to use "Quoted Printable" encoding instead of whatever I'm using, however I already have the following set on the config of the message:

```cs
mailMergeMessage.Config.TextTransferEncoding = ContentEncoding.QuotedPrintable;
```

Looking into the repository a little it looks like you may be defaulting the encoding to 7-bit instead:

```cs
                ContentTransferEncoding = Tools.IsSevenBit(DocHtml)
                    ? ContentEncoding.SevenBit
                    : TextTransferEncoding != ContentEncoding.SevenBit
                        ? TextTransferEncoding
                        : ContentEncoding.QuotedPrintable,
```

https://github.com/axuno/MailMergeLib/blob/78e2336dfa18f3791ad89ca7ad4f506091082792/MailMergeLib/HtmlBodyBuilder.cs **Line 98**

I may be way off with this, but it seems that I am setting the message to use `QuotedPrintable` but still getting the dot stuffing issue.

Any ideas?

**Comment by axunonb** [comment] 2018-02-26 18:19
First: **Dot Stuffing**
We never experienced this problem with the current ```SmtpClient``` and I'm confident it works well. Still, confident does not mean sure. Could you submit a sample to reproduce. As you already googled you also noticed that this _could_ be an issue with the SMTP server. Let's check it.

**Comment by axunonb** [comment] 2018-02-26 18:25
Second: **Setting ContentTransferEncoding**
Yes, you are right: ```ContentEncoding.QuotedPrintable``` is only used if really necessary, because it leads to smaller message size. This is a relict left over from the early beginnings, and I agree this should be removed. I'll update the repo so it will be included in the next release. As a quick fix include any character above ASCII 127 in the text, best probably a non-breaking space over the keyboard with ```alt(0160)```, to enforce ```ContentEncoding.QuotedPrintable```.

**Comment by hades200082** [comment] 2018-02-27 09:24
To respond to your first comment, the SMTP server is SendGrid and it has been used previously to send emails via several other systems with no issue.

I'll see how forcing QuotedPrintable works and come back to you... it may be a week or so before I get to work on that project again though.

**Comment by axunonb** [comment] 2018-03-10 12:17
Included in new release https://github.com/axuno/MailMergeLib/releases/tag/v5.4.1.0

**Closed as completed by axunonb** 2018-03-10 12:17 UTC
Labels: enhancement

**Comment by hades200082** [comment] 2018-04-13 08:25
We finally have more info on this.  Even with the forcible addition of the non-breaking space character to every email we've had some emails go out with missing dots.

The effect is broken images or links that don't work.

The oddity is that even on emails where every message sent is identical, we are seeing the breakages only in some messages.  Also, each broken email message may be broken in a different way (i.e. different images/links appearing broken to different recipients and some people getting unbroken messages)

I've confirmed that this is 100% a mailmergelib issue.  Sending the same email message to a recipient that got a broken one using the standard .Net SMTP mailer didn't reproduce the issue.

Also, I've had MailMergeLib simply output the .msg files to a directory instead of sending them and the issue still manifests in those .msg files when opened in a mail client.

I'm not sure what else to try.

**Comment by axunonb** [comment] 2018-04-13 16:31
Lee
Very good, these hints are useful to further investigate. Could you send me the test solution where the broken images can be reproduced, because whatever I tried, I couldn't.

**Comment by axunonb** [comment] 2018-04-16 21:37
Lee, I simply cannot reproduce your issue. What are you doing different than this:
```csharp
private static void Send1000InlineImages()
{
    var images = new StringBuilder();
    for (var i = 1; i <= 1000; i++)
    {
        images.AppendFormat($"<img src=\"file:///green.gif\" alt=\"{i}\" width=\"50\" height=\"50\" />");
        if (i % 10 == 0) images.Append("<br/>");
    }

    var htmlWithImg =
        "<html>" +
        "<head><title>Send email with images</title></head>" +
        "<body>" + images +
        "</body>" +
        "</html>";

    var mmm = new MailMergeMessage("Image Test", "plain text", htmlWithImg);
    mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, "joe@doe.com"));
    mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "liza@doe.com"));
    mmm.Config.TextTransferEncoding = ContentEncoding.QuotedPrintable; // same with ContentEncoding.SevenBit

    var mms = new MailMergeSender();
    // set sender config here
    for (var i = 0; i < 1000; i++)
    {
        mms.Send(mmm, (object) null);
    }
}
```
In my tests all emails show images displayed correctly using this green 10x10 pixel gif (Outlook 2016).
![green](https://user-images.githubusercontent.com/10255664/38836490-9f04a8b4-41ce-11e8-9ca3-bf1ca352a40d.gif)

**Comment by hades200082** [comment] 2018-04-20 10:55
Hi.

Here's the code from the method that handles the sending in our application.

```csharp
// PrepareEmailTemplate returns plain HTML as a string. Its job is to switch links with trackable links in our CMS 
// The links are valid when inspected at this point
var template = PrepareEmailTemplate(splitEmail?.HTML_BODY ?? email.HTML_BODY, kNewsLetterIssue, kNewsletter, kSite);

var mailMergeMessage = new MailMergeMessage(splitEmail?.SUBJECT ?? email.SUBJECT)
{
    HtmlText = template
};
mailMergeMessage.ConvertHtmlToPlainText();

var senderEmail = ConfigurationManager.AppSettings["SenderEmail"] ?? "Undefined";
var senderName = ConfigurationManager.AppSettings["SenderName"] ?? "Undefined";
            
mailMergeMessage.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, senderName, senderEmail));
mailMergeMessage.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.ReplyTo, email.SENDER_NAME, email.REPLY_TO_EMAIL));
mailMergeMessage.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, "{FirstName} {LastName}", "{Email}"));

// These additional headers are added to allow our bounce tracking to work.
mailMergeMessage.Headers.Add("X-CMS-IssueID", kNewsLetterIssue.IssueID.ToString());
mailMergeMessage.Headers.Add("X-CMS-SubscriberID", "0");
mailMergeMessage.Headers.Add("X-CMS-ContactID", "{ContactId}");
mailMergeMessage.Headers.Add("X-REGIONS-EmailID", email.ID.ToString());


// Message config
mailMergeMessage.Config.CharacterEncoding = Encoding.UTF8;
mailMergeMessage.Config.CultureInfo = new CultureInfo(kSite.DefaultVisitorCulture); // "en-gb"
mailMergeMessage.Config.IgnoreIllegalRecipientAddresses = true;
mailMergeMessage.Config.Organization = "Our name";
mailMergeMessage.Config.Priority = MessagePriority.Normal;
mailMergeMessage.Config.SmartFormatterConfig.FormatErrorAction = ErrorAction.MaintainTokens;
mailMergeMessage.Config.SmartFormatterConfig.ParseErrorAction = ErrorAction.MaintainTokens;
mailMergeMessage.Config.SmartFormatterConfig.CaseSensitivity = CaseSensitivityType.CaseInsensitive;
mailMergeMessage.Config.SmartFormatterConfig.ConvertCharacterStringLiterals = true;
mailMergeMessage.Config.TextTransferEncoding = ContentEncoding.QuotedPrintable;
mailMergeMessage.Config.BinaryTransferEncoding = ContentEncoding.Base64;


var outputDirectory = ConfigurationHelper.GetAppSetting<string>("SMTP.IisPickupDirectory");

if (outputDirectory.IsNullOrWhiteSpace())
{
    // Must have an output directory for sending
    throw new Exception("An output directory must be specified for live mode sending.");
}

if (outputDirectory.StartsWith("/") || outputDirectory.StartsWith("~"))
{
    outputDirectory =
        HostingEnvironment.MapPath(outputDirectory);
}



if (!Directory.Exists(outputDirectory))
{
    Directory.CreateDirectory(outputDirectory);
}

var smtpConfig = new SmtpClientConfig
{
    Name = "Email Folder Output",
    MessageOutput = MessageOutput.Directory,
    MailOutputDirectory = outputDirectory
};

var mailMergeSender = new MailMergeSender
{
    Config = new SenderConfig
    {
        MaxNumOfSmtpClients = 50,
        SmtpClientConfig = new[]
        {
            smtpConfig
        }
    }
};

try
{
    mailMergeSender.Send(mailMergeMessage, recipients);
}
catch (Exception ex)
{
    EventLogProvider.LogException("REGIONS_SEND", "ERROR", ex, 0, "An error occurred when sending emails.");
    throw; // rethrow to ensure crash & resume
}
finally
{
    mailMergeMessage.Dispose();
    mailMergeSender.Dispose();
}
```

This generates the .eml files in the IIS Pickup directory.  I have a config key for that location so when running locally or in our staging environment we set it to a different location so that we can inspect the .eml files.

We open the .eml files in Thunderbird to check them.  Sometimes we'll drop them into the pickup directory manually to send them to Email On Acid. When inspecting the .eml files we have had instances where dots have gone missing from the URLs of links and images.

I hope this helps get to the bottom of the issue. It's driving me nuts.

**Comment by axunonb** [comment] 2018-04-21 12:10
#### General remark

We now understand you're not sending emails to SendGrid or Acid directly. Instead, IIS SMTP Sever
is being used as a relay. This makes a **big** difference here.

#### Content needed

We can't get to the bottom of the problem when only looking at the code to generate the message. Your code sample is perfectly okay. We need the content as well.

So first let's generate the HTML part of a message with images loaded from a webserver:

```Csharp
private static string GetHtmlPart()
{
	var images = new StringBuilder();
	for (var i = 1; i <= 1000; i++)
	{
        // this is the image file posted in this issue earlier
		images.AppendFormat($"<img src=\"https://user-images.githubusercontent.com/10255664/38836490-9f04a8b4-41ce-11e8-9ca3-bf1ca352a40d.gif\" alt=\"{i}\" width=\"50\" height=\"50\" />");
		if (i % 10 == 0) images.Append("<br/>");
	}

	var htmlWithImg =
		"<html>" +
		"<head><title>Send email with images</title></head>" +
		"<body>" + images +
		"</body>" +
		"</html>";

	return htmlWithImg;
}
```

#### System.Net.Mail Behavior:

```Csharp
var htmlWithImg = GetHtmlPart();
var mailMsg = new System.Net.Mail.MailMessage("liza@doe.com", "joe@doe.com", "Image Test", "plain text");
var htmlStream = new MemoryStream();
var htmlSw = new StreamWriter(htmlStream);
htmlSw.Write(htmlWithImg);
htmlStream.Position = 0;
mailMsg.AlternateViews.Add(new AlternateView(htmlStream){ContentType = new System.Net.Mime.ContentType("text/html"), TransferEncoding = TransferEncoding.QuotedPrintable });
var smtpClient = new System.Net.Mail.SmtpClient
{
	DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory,
	PickupDirectoryLocation = @"Path-to-output-directory"
};
smtpClient.Send(mailMsg);
```
This produces on EML file (System-Net-Mail-SmtpClient_QuotedPrintable.eml). **When you open it with Thunderbird or Outlook, you will notice that some of the images are not displayed**. To be precise:

All URLs are affected, which start with a dot at the beginning of line. This is because ```System.Net.Mail.SmtpClient``` inserts a second dot right after the first of a line. To get rid of this dot stuffing, you simply change the ```ContentType``` to ```TransferEncoding.Base64``` and voilà, all images are displayed correctly, because Base64 encoding does not contain any dots (System-Net-Mail-SmtpClient_Base64.eml)

#### MailMergeLib Behavior

```Csharp
var htmlWithImg = GetHtmlPart();
var mmm = new MailMergeMessage("Image Test", "plain text", htmlWithImg);
mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, "joe@doe.com"));
mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "liza@doe.com"));
mmm.Config.TextTransferEncoding = ContentEncoding.QuotedPrintable;

var mms = new MailMergeSender();
mms.Config.SmtpClientConfig[0].MessageOutput = MessageOutput.Directory;
mms.Config.SmtpClientConfig[0].MailOutputDirectory = @"Path-to-output-directory";
mms.Send(mmm, (object) null);
```
When opening this EML file (MailMergeLib_QuotedPrintable.eml) with Thunderbird or Outlook, **it will show all images intact from the very beginning**. There is no dot stuffing.

#### IIS SMTP Server

When using IIS SMTP Server as a relay, EML files are obviously expected to have single dots at the beginning of a line replaced with double dots. In case there is only a single dot, it is just eaten up.

This can be overcome by

* only using ```ContentEncoding.Base64``` in ```MailMergeLib``` (least obtrusive) 
* not using IIS SMTP Server with EML files, but with SMTP protocol (second least obtrusive)
* replacing single dots with double dots before transfering EML files to the pickup directory
* not using IIS SMTP Server as a relay at all

Generally, dot stuffing should actually be the concern of IIS SMTP Server *when forwarding the message*,
but not the concern of the client which is expected to produce standard compliant EML files.

#### Conclusions

* We still can't reproduce that EML files created from ```MailMergeLib``` have missing dots. It rather looks like the dots get lost when IIS SMTP Server sends these files. Creating EML files is done using ```MimeKit```'s ```MimeMessage.WriteTo``` method. For this repository no "dot related issues" are reported.
* In order to track this issue further, we need a working sample which produces malformatted EML files. Our conclusion for now is, that IIS SMTP Server is the source of the problem.

Looking forward to your comments on this.

**Comment by axunonb** [comment] 2018-04-21 12:13
#### General remark

We now understand you're not sending emails to SendGrid or Acid directly. Instead, IIS SMTP Sever
is being used as a relay. This makes a **big** difference here.

#### Content needed

We can't get to the bottom of the problem when only looking at the code to generate the message. Your code sample is perfectly okay. We need the content as well.

So first let's generate the HTML part of a message with images loaded from a webserver:

```Csharp
private static string GetHtmlPart()
{
	var images = new StringBuilder();
	for (var i = 1; i <= 1000; i++)
	{
        // this is the image file posted in this issue earlier
		images.AppendFormat($"<img src=\"https://user-images.githubusercontent.com/10255664/38836490-9f04a8b4-41ce-11e8-9ca3-bf1ca352a40d.gif\" alt=\"{i}\" width=\"50\" height=\"50\" />");
		if (i % 10 == 0) images.Append("<br/>");
	}

	var htmlWithImg =
		"<html>" +
		"<head><title>Send email with images</title></head>" +
		"<body>" + images +
		"</body>" +
		"</html>";

	return htmlWithImg;
}
```

#### System.Net.Mail Behavior:

```Csharp
var htmlWithImg = GetHtmlPart();
var mailMsg = new System.Net.Mail.MailMessage("liza@doe.com", "joe@doe.com", "Image Test", "plain text");
var htmlStream = new MemoryStream();
var htmlSw = new StreamWriter(htmlStream);
htmlSw.Write(htmlWithImg);
htmlStream.Position = 0;
mailMsg.AlternateViews.Add(new AlternateView(htmlStream){ContentType = new System.Net.Mime.ContentType("text/html"), TransferEncoding = TransferEncoding.QuotedPrintable });
var smtpClient = new System.Net.Mail.SmtpClient
{
	DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory,
	PickupDirectoryLocation = @"Path-to-output-directory"
};
smtpClient.Send(mailMsg);
```
This produces on EML file (System-Net-Mail-SmtpClient_QuotedPrintable.eml). **When you open it with Thunderbird or Outlook, you will notice that some of the images are not displayed**. To be precise:

All URLs are affected, which start with a dot at the beginning of line. This is because ```System.Net.Mail.SmtpClient``` inserts a second dot right after the first of a line. To get rid of this dot stuffing, you simply change the ```ContentType``` to ```TransferEncoding.Base64``` and voilà, all images are displayed correctly, because Base64 encoding does not contain any dots (System-Net-Mail-SmtpClient_Base64.eml)

#### MailMergeLib Behavior

```Csharp
var htmlWithImg = GetHtmlPart();
var mmm = new MailMergeMessage("Image Test", "plain text", htmlWithImg);
mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, "joe@doe.com"));
mmm.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "liza@doe.com"));
mmm.Config.TextTransferEncoding = ContentEncoding.QuotedPrintable;

var mms = new MailMergeSender();
mms.Config.SmtpClientConfig[0].MessageOutput = MessageOutput.Directory;
mms.Config.SmtpClientConfig[0].MailOutputDirectory = @"Path-to-output-directory";
mms.Send(mmm, (object) null);
```
When opening this EML file (MailMergeLib_QuotedPrintable.eml) with Thunderbird or Outlook, **it will show all images intact from the very beginning**. There is no dot stuffing.

#### IIS SMTP Server

When using IIS SMTP Server as a relay, EML files are obviously expected to have single dots at the beginning of a line replaced with double dots. In case there is only a single dot, it is just eaten up.

This can be overcome by

* only using ```ContentEncoding.Base64``` in ```MailMergeLib``` (least obtrusive) 
* not using IIS SMTP Server with EML files, but with SMTP protocol (second least obtrusive)
* replacing single dots with double dots before transfering EML files to the pickup directory
* not using IIS SMTP Server as a relay at all

Generally, dot stuffing should actually be the concern of IIS SMTP Server *when forwarding the message*,
but not the concern of the client which is expected to produce standard compliant EML files.

#### Conclusions

* We still can't reproduce that EML files created from ```MailMergeLib``` have missing dots. It rather looks like the dots get lost when IIS SMTP Server sends these files. Creating EML files is done using ```MimeKit```'s ```MimeMessage.WriteTo``` method. For this repository no "dot related issues" are reported.
* In order to track this issue further, we need a working sample which produces malformatted EML files. Our conclusion for now is, that IIS SMTP Server is the source of the problem.

Looking forward to your comments on this.
[EML-Samples.zip](https://github.com/axuno/MailMergeLib/files/1934470/EML-Samples.zip)

**Comment by hades200082** [comment] 2018-04-23 08:26
Hi

I had suspicions that this might be the case. Thank you for confirming them.  I think we'll switch to Base64 and see how that goes.

Thanks for the help.

Regards

Lee
